server:
  shutdown: graceful
  port: 5001

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
    database: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root-pass
    url: jdbc:mysql://localhost:3306/order?useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      minimum-idle: 10
      maximum-pool-size: 100