server:
  shutdown: graceful
  port: 5001

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root-pass
    url: jdbc:mysql://localhost:3306/order?serverTimeZone=UTC&characterEncoding=UTF-8