### 오더 등록
POST http://localhost:5001/api/orders
Content-Type: application/json

{
  "orderNumber" : "1"
}

### 오더 조회
GET http://localhost:5001/api/orders/2

### 오더 번호 업데이트
PUT http://localhost:5001/api/orders/1/update-order-number
Content-Type: application/json

{
  "orderNumber" : "1-5"
}