spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpalock?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true