version: "3.7"
services:
  order-db:
    image: mysql:5.7.20
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=order
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=order-svc
      - MYSQL_PASSWORD=order-svc-pass
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci