spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
          headers: ["uuid"]
      bindings:
        messageChannel:
          binder: kafka
          destination: test-message-stream
          producer:
            header-mode: headers
            partition-key-expression: headers['uuid']
            sync: true
      default-binder: kafka