version: "3.7"
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=svc-user
      - MYSQL_PASSWORD=svc-pass
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
    volumes:
      - ./cache/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
