server:
  port: 8081
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
          headers: ["uuid"]
      bindings:
        testEventChannel:
          binder: kafka
          destination: test-message-stream
          content-type: application/json
          consumer:
            header-mode: embeddedHeaders
            checkpointMode: record
      default-binder: kafka