my-application:
  name: configTestApplication
  version: 1.0.0.RELEASE
  releaseDate: 2023.08.01
  developers:
    - name: youngchul.shin
      email: youngchul.shin@config-test.com
      company: configTestCompany
      phone: 01011112222
      skills:
        - backend
        - client
    - name: go1323
      email: go1323@config-test.com
      company: configTestCompany
      phone: 01033334444
      skills:
        - frontend

my-application-v2:
  name: configTestApplication
  version: 1.0.0.RELEASE
  releaseDate: 2023.08.01
  developers:
    - name: youngchul.shin
      email: youngchul.shin@config-test.com
      company: configTestCompany
      phone: 01011112222
      skills:
        - backend
        - client
    - name: go1323
      email: go1323@config-test.com
      company: configTestCompany
      phone: 01033334444
      skills:
        - frontend

my-application-v3:
  name: configTestApplication
  version: 1.0.0.RELEASE
  releaseDate: 2023.08.01
  developers:
    - name: youngchul.shin
      email: youngchul.shin@config-test.com
      company: configTestCompany
      phone: 01011112222
      skills:
        - backend
        - client
    - name: go1323
      email: go1323@config-test.com
      company: configTestCompany
      phone: 01033334444
      skills:
        - frontend