spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/test?
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1323

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    task.agile: debug
    org.springframework.security: debug
