version: "3.8"
services:
  redis:
    image: redis:7.0.5
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - ~/redis/redis.conf:/user/local/etc/redis/redis.conf
    command:
      - redis-server
      - /user/local/etc/redis/redis.conf