spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liquibase
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db-yaml/changelog-master.yml
#    change-log: classpath:/db/changelog-master.xml