
spring:
  datasource:
    username: user
    password: user_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my-db
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false