
spring:
  datasource:
    username: user
    password: user_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my-db
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      jakarta:
        persistence:
          query:
            timeout: 5000

application:
  create-init-data: false