spring:
  datasource:
    url: jdbc:mysql://localhost:3306/openapi
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create
