myValue:
  value1: testValue

spring:
  jpa:
    show-sql: true
  datasource:
    username: root
    password: 1323
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_test