version: "3.7"
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=spring_test
      - MYSQL_ROOT_PASSWORD=1323
      - MYSQL_USER=svc-user
      - MYSQL_PASSWORD=1323
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci