# @see https://swagger.io/specification/
openapi: '3.0.1'

info:
  title: 'open-api-spec-generate-test'
  description: 'OAS을 이용해서 API code를 생성하는 테스트를 합니다'
  version: '0.0.1'

servers:
  - url: http://localhost:8080
    description: local server

externalDocs:
  description: '샘플 코드'
  url: https://github.com/YoungChulShin/study-spring/tree/master/04.open-api-spec-generate

paths:
  /hello:
    get:
      description: '쿼리 파라미터 기준으로 인사를 합니다'
      tags:
        - hello
      parameters:
        - $ref: '#/components/parameters/NameParam'
      responses:
        '200':
          $ref: '#/components/responses/GetHelloResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'

  /hello/{name}:
    get:
      description: 'Path variable 기준으로 인사를 합니다'
      tags:
        - hello
      parameters:
        - $ref: '#/components/parameters/NamePathParam'
      responses:
        '200':
          $ref: '#/components/responses/GetHelloResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'

  /hello/remember:
    post:
      description: 'member 정보를 추가합니다'
      tags:
        - hello
      requestBody:
        $ref: '#/components/requestBodies/HelloRememberRequest'
      responses:
        '200':
          $ref: '#/components/responses/PostHelloRememberResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'

components:
  schemas:

    #----------------------------------------
    # Common Schema
    #----------------------------------------
    AddressDto:
      description: '주소 정보 Dto'
      type: object
      properties:
        fullAddress:
          type: string
          description: '전체 주소'
          nullable: false
        bunji:
          type: string
          description: '번지'
          nullable: false
        roadName:
          type: string
          description: '도로명'
          nullable: false

    APIResult:
      description: |
        - API 결과 응답
        - SUCCESS: 성공
        - FAIL: 실패
      type: string
      enum:
        - SUCCESS
        - FAIL

    #----------------------------------------
    # Common API Response
    #----------------------------------------
    CommonErrorResponse:
      type: object
      properties:
        result:
          $ref: '#/components/schemas/APIResult'
        data:
          type: string
          nullable: true
          example: null
        message:
          type: string
          description: '에러 메시지'
          nullable: true
        errorCode:
          type: string
          description: '에러 코드'
          nullable: true
          example: 'COMMON_SYSTEM_ERROR'

    CommonApiResponse:
      description: '공통 API 응답 필드 리스트'
      type: object
      properties:
        result:
          $ref: '#/components/schemas/APIResult'
        message:
          type: string
          description: '응답 메시지'
          nullable: true
          example: null
        errorCode:
          type: string
          description: '에러 코드'
          nullable: true
          example: null

  parameters:
    NameParam:
      name: name
      in: query
      description: '사용자 이름'
      required: true
      deprecated: false
      allowEmptyValue: false
      schema:
        type: string

    NamePathParam:
      name: name
      in: path
      description: '사용자 이름'
      required: true
      allowEmptyValue: false
      schema:
        type: string

  requestBodies:

    #----------------------------------------
    # HelloController Request
    #----------------------------------------
    HelloRememberRequest:
      description: 'Hello Remember 요청'
      content:
        application.json:
          schema:
            type: object
            properties:
              name:
                type: string
                nullable: false
              age:
                type: integer
                nullable: false
                minimum: 0
                maximum: 100
              address:
                $ref: '#/components/schemas/AddressDto'

  responses:

    #----------------------------------------
    # Common Responses
    #----------------------------------------
    Created:
      description: Created

    Accepted:
      description: Accepted

    NoContent:
      description: No Content

    BadRequest:
      description: Bad Request
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/CommonErrorResponse'

    NotFound:
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/CommonErrorResponse'

    ServerError:
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/CommonErrorResponse'

    #----------------------------------------
    # HelloController Responses
    #----------------------------------------
    GetHelloResponse:
      description: 'OK'
      content:
        application.json:
          schema:
            allOf:
              - type: object
                properties:
                  data:
                    type: string
                    nullable: true
                    example: 'Hello, youngchul'
              - $ref: '#/components/schemas/CommonApiResponse'

    PostHelloRememberResponse:
      description: 'OK'
      content:
        application.json:
          schema:
            allOf:
              - type: object
                properties:
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                        description: '이름'
                        nullable: false
                        example: '영철'
                      age:
                        type: integer
                        description: '나이'
                        nullable: false
                        example: 20
                      address:
                        $ref: '#/components/schemas/AddressDto'
              - $ref: '#/components/schemas/CommonApiResponse'