server:
  port: 8090

system-info:
  external-call:
    type: openfeign

# open feign
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: basic