version: "3.8"
services:
  mysql:
    image: mysql:5.7.32
    container_name: school-reactive-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_password
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    command: mysqld --skip-ssl --character_set_server=utf8mb4 --lower_case_table_names=1